# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        pretty

# Server
source:           docs
destination:      _gh_pages
host:             0.0.0.0
port:             9001
baseurl:          /
url:              http://localhost:9001

# Custom vars
current_version:  0.0.1
repo:             https://github.com/jboho/framework

download:
  source:         https://github.com/jboho/framework/archive/master.zip
